/*
 * FastaExportAlignFrame.java
 *
 * Created on 2010-07-03, 19:46:28
 */
package jmhc.forms;

import java.io.File;
import java.util.ArrayList;
import java.util.Dictionary;
import java.util.Hashtable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import jmhc.processing.FastaExportAndAlignment;
import jmhc.objects.DBSettings;
import jmhc.objects.MuscleEnum;
import jmhc.objects.PathChecker;
import jmhc.tools.SeqUtils;

/**
 *
 * @author Michal Stuglik
 */
public class FastaExportAlignFrame extends javax.swing.JInternalFrame {

    private Preferences prefs;
    private ProgramControler ProgramControler;
    private JLabel jLabel_statusLabel;
    private int minLength;
    private FastaExportAndAlignment mFastaExportAndAlignment = null;

    public int getMinLength() {
        return minLength;
    }

    public void setMinLength(int minLength) {
        if (minLength <= 0) {
            minLength = 0;
        }
        this.minLength = minLength;
    }
    private int maxLength;

    public int getMaxLength() {
        return maxLength;
    }

    public void setMaxLength(int maxLength) {
        if (maxLength <= 0) {
            maxLength = 0;
        }
        this.maxLength = maxLength;
    }
    private String folderPath;

    public String getFolderPath() {
        return folderPath;
    }

    public void setFolderPath(String folderPath) {
        this.folderPath = folderPath;
    }
    private String prefix;

    public String getPrefix() {
        return prefix;
    }

    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }
    private String muscleFile;

    /** Creates new form FastaExportAlignFrame */
    public FastaExportAlignFrame(ProgramControler mProgramControler, JLabel jLabel_statusLabel) {
        initComponents();

        // create a Preferences instance (somewhere later in the code)
        prefs = Preferences.userNodeForPackage(this.getClass());
        this.ProgramControler = mProgramControler;
        this.jLabel_statusLabel = jLabel_statusLabel;

        for (int i = 0; i < SeqUtils.getFileNamesInExport().size(); i++) {
            String item = SeqUtils.getFileNamesInExport().get(i);

            jComboBox_name1.insertItemAt(item, i);
            jComboBox_name2.insertItemAt(item, i);
            jComboBox_name3.insertItemAt(item, i);
            jComboBox_name4.insertItemAt(item, i);
        }

        jComboBox_name1.setSelectedIndex(1);
        jComboBox_name2.setSelectedIndex(2);
        jComboBox_name3.setSelectedIndex(3);
        jComboBox_name4.setSelectedIndex(4);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Main = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox_alignment = new javax.swing.JCheckBox();
        jCheckBox_sortOrignialFasta = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jButton_muscleOutput = new javax.swing.JButton();
        jTextField_muscleOutput = new javax.swing.JTextField();
        jButton_start = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTextField_prefix = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_minLength = new javax.swing.JTextField();
        jTextField_maxLength = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_minNumSeq = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_variantCount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox_name1 = new javax.swing.JComboBox();
        jComboBox_name2 = new javax.swing.JComboBox();
        jComboBox_name3 = new javax.swing.JComboBox();
        jComboBox_name4 = new javax.swing.JComboBox();
        jPanel8 = new javax.swing.JPanel();
        jCheckBox_anchors = new javax.swing.JCheckBox();
        jCheckBox_brenner = new javax.swing.JCheckBox();
        jCheckBox_dimer = new javax.swing.JCheckBox();
        jCheckBox_diags = new javax.swing.JCheckBox();
        jButton_close = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setIconifiable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(jmhc.forms.JMHCApp.class).getContext().getResourceMap(FastaExportAlignFrame.class);
        setTitle(resourceMap.getString("Export/Alignment.title")); // NOI18N
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(613, 650));
        setName("Export/Alignment"); // NOI18N
        setVisible(true);

        jPanel_Main.setName("jPanel_Main"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), resourceMap.getString("jPanel6.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION)); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true), resourceMap.getString("jPanel4.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION)); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(resourceMap.getString("jTextArea1.text")); // NOI18N
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jCheckBox_alignment.setText(resourceMap.getString("jCheckBox_alignment.text")); // NOI18N
        jCheckBox_alignment.setName("jCheckBox_alignment"); // NOI18N

        jCheckBox_sortOrignialFasta.setText(resourceMap.getString("jCheckBox_sortOrignialFasta.text")); // NOI18N
        jCheckBox_sortOrignialFasta.setName("jCheckBox_sortOrignialFasta"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jCheckBox_alignment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox_sortOrignialFasta))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_alignment)
                    .addComponent(jCheckBox_sortOrignialFasta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true), resourceMap.getString("jPanel7.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION)); // NOI18N
        jPanel7.setName("jPanel7"); // NOI18N

        jButton_muscleOutput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmhc/forms/resources/open16.gif"))); // NOI18N
        jButton_muscleOutput.setText(resourceMap.getString("jButton_muscleOutput.text")); // NOI18N
        jButton_muscleOutput.setName("jButton_muscleOutput"); // NOI18N
        jButton_muscleOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_muscleOutputActionPerformed(evt);
            }
        });

        jTextField_muscleOutput.setBackground(resourceMap.getColor("jTextField_muscleOutput.background")); // NOI18N
        jTextField_muscleOutput.setEditable(false);
        jTextField_muscleOutput.setName("jTextField_muscleOutput"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_muscleOutput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_muscleOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_muscleOutput)
                    .addComponent(jTextField_muscleOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jButton_start.setIcon(resourceMap.getIcon("jButton_start.icon")); // NOI18N
        jButton_start.setText(resourceMap.getString("jButton_start.text")); // NOI18N
        jButton_start.setName("jButton_start"); // NOI18N
        jButton_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_startActionPerformed(evt);
            }
        });

        jSplitPane1.setDividerLocation(290);
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setLastDividerLocation(280);
        jSplitPane1.setMaximumSize(new java.awt.Dimension(551, 230));
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true), resourceMap.getString("jPanel5.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION)); // NOI18N
        jPanel5.setName("jPanel5"); // NOI18N

        jTextField_prefix.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_prefix.setName("jTextField_prefix"); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField_prefix, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_prefix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true), resourceMap.getString("jPanel6.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION)); // NOI18N
        jPanel6.setName("jPanel6"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jTextField_minLength.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_minLength.setHighlighter(null);
        jTextField_minLength.setName("jTextField_minLength"); // NOI18N

        jTextField_maxLength.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_maxLength.setHighlighter(null);
        jTextField_maxLength.setName("jTextField_maxLength"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jTextField_minNumSeq.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_minNumSeq.setText(resourceMap.getString("jTextField_minNumSeq.text")); // NOI18N
        jTextField_minNumSeq.setHighlighter(null);
        jTextField_minNumSeq.setName("jTextField_minNumSeq"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jTextField_variantCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_variantCount.setToolTipText(resourceMap.getString("jTextField_variantCount.toolTipText")); // NOI18N
        jTextField_variantCount.setHighlighter(null);
        jTextField_variantCount.setName("jTextField_variantCount"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_variantCount, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(jTextField_minNumSeq, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_maxLength, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_minLength, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField_maxLength, jTextField_minLength, jTextField_minNumSeq, jTextField_variantCount});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_minLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_maxLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_minNumSeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_variantCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField_maxLength, jTextField_minLength, jTextField_minNumSeq, jTextField_variantCount});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel5, jPanel6});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel9.setName("jPanel9"); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true), resourceMap.getString("jPanel3.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION)); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        jComboBox_name1.setMaximumSize(new java.awt.Dimension(90, 22));
        jComboBox_name1.setMinimumSize(new java.awt.Dimension(90, 22));
        jComboBox_name1.setName("jComboBox_name1"); // NOI18N
        jComboBox_name1.setPreferredSize(new java.awt.Dimension(90, 22));

        jComboBox_name2.setMaximumSize(new java.awt.Dimension(90, 22));
        jComboBox_name2.setMinimumSize(new java.awt.Dimension(90, 22));
        jComboBox_name2.setName("jComboBox_name2"); // NOI18N
        jComboBox_name2.setPreferredSize(new java.awt.Dimension(90, 22));

        jComboBox_name3.setMaximumSize(new java.awt.Dimension(90, 22));
        jComboBox_name3.setMinimumSize(new java.awt.Dimension(90, 22));
        jComboBox_name3.setName("jComboBox_name3"); // NOI18N
        jComboBox_name3.setPreferredSize(new java.awt.Dimension(90, 22));

        jComboBox_name4.setMaximumSize(new java.awt.Dimension(90, 22));
        jComboBox_name4.setMinimumSize(new java.awt.Dimension(90, 22));
        jComboBox_name4.setName("jComboBox_name4"); // NOI18N
        jComboBox_name4.setPreferredSize(new java.awt.Dimension(90, 22));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_name3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_name4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBox_name1, jComboBox_name2, jComboBox_name3, jComboBox_name4});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jComboBox_name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_name3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_name4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBox_name1, jComboBox_name2, jComboBox_name3, jComboBox_name4});

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true), resourceMap.getString("jPanel8.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION)); // NOI18N
        jPanel8.setName("jPanel8"); // NOI18N

        jCheckBox_anchors.setSelected(true);
        jCheckBox_anchors.setText(resourceMap.getString("jCheckBox_anchors.text")); // NOI18N
        jCheckBox_anchors.setToolTipText(resourceMap.getString("jCheckBox_anchors.toolTipText")); // NOI18N
        jCheckBox_anchors.setName("jCheckBox_anchors"); // NOI18N

        jCheckBox_brenner.setText(resourceMap.getString("jCheckBox_brenner.text")); // NOI18N
        jCheckBox_brenner.setToolTipText(resourceMap.getString("jCheckBox_brenner.toolTipText")); // NOI18N
        jCheckBox_brenner.setName("jCheckBox_brenner"); // NOI18N

        jCheckBox_dimer.setText(resourceMap.getString("jCheckBox_dimer.text")); // NOI18N
        jCheckBox_dimer.setToolTipText(resourceMap.getString("jCheckBox_dimer.toolTipText")); // NOI18N
        jCheckBox_dimer.setName("jCheckBox_dimer"); // NOI18N

        jCheckBox_diags.setText(resourceMap.getString("jCheckBox_diags.text")); // NOI18N
        jCheckBox_diags.setToolTipText(resourceMap.getString("jCheckBox_diags.toolTipText")); // NOI18N
        jCheckBox_diags.setName("jCheckBox_diags"); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_anchors)
                    .addComponent(jCheckBox_brenner)
                    .addComponent(jCheckBox_diags)
                    .addComponent(jCheckBox_dimer))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jCheckBox_anchors)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_brenner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_dimer)
                .addGap(3, 3, 3)
                .addComponent(jCheckBox_diags)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel8.getAccessibleContext().setAccessibleName(resourceMap.getString("jPanel8.AccessibleContext.accessibleName")); // NOI18N

        jSplitPane1.setRightComponent(jPanel9);

        jButton_close.setIcon(resourceMap.getIcon("jButton_close.icon")); // NOI18N
        jButton_close.setText(resourceMap.getString("jButton_close.text")); // NOI18N
        jButton_close.setMaximumSize(new java.awt.Dimension(81, 25));
        jButton_close.setMinimumSize(new java.awt.Dimension(81, 25));
        jButton_close.setName("jButton_close"); // NOI18N
        jButton_close.setPreferredSize(new java.awt.Dimension(81, 25));
        jButton_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton_start)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                        .addComponent(jButton_close, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_start))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_MainLayout = new javax.swing.GroupLayout(jPanel_Main);
        jPanel_Main.setLayout(jPanel_MainLayout);
        jPanel_MainLayout.setHorizontalGroup(
            jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_MainLayout.setVerticalGroup(
            jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_startActionPerformed
        try {
            if (ProgramControler.DBSettings.getMSQLite() == null) {
                throw new Exception(ProgramControler.DBSettings.exc_connectToDataBase);
            }

            if (jButton_start.getText().equals("start")) {

                mFastaExportAndAlignment = new FastaExportAndAlignment(ProgramControler, jLabel_statusLabel, this);
                this.InitialSettings();
                mFastaExportAndAlignment.StartProcessing();
                SetsForProcessing(true);

            } else if (jButton_start.getText().equals("stop")) {

                mFastaExportAndAlignment.interrupt();
            }

        } catch (Exception ex) {
            Logger.getLogger(DBSettings.loggerProgram).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), this.getName(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_startActionPerformed

    private void InitialSettings() throws Exception {
        try {

            //Data base settings
            if (this.ProgramControler.DBSettings == null || this.ProgramControler.DBSettings.getMSQLite() == null) {
                throw new Exception("Connect to data base");
            }

            folderPath = this.jTextField_muscleOutput.getText();
            if (folderPath == null || folderPath.isEmpty()) {
                throw new Exception("Set output folder!");
            }
            mFastaExportAndAlignment.setFolderPath(folderPath);

            //output name stuff:
            List<Object> nameOptions = new ArrayList<Object>();
            if (!jComboBox_name1.getSelectedItem().toString().isEmpty()) {
                nameOptions.add(jComboBox_name1.getSelectedItem());
            }
            if (!jComboBox_name2.getSelectedItem().toString().isEmpty()) {
                nameOptions.add(jComboBox_name2.getSelectedItem());
            }
            if (!jComboBox_name3.getSelectedItem().toString().isEmpty()) {
                nameOptions.add(jComboBox_name3.getSelectedItem());
            }
            if (!jComboBox_name4.getSelectedItem().toString().isEmpty()) {
                nameOptions.add(jComboBox_name4.getSelectedItem());
            }
            mFastaExportAndAlignment.setNameOptions(nameOptions);

            mFastaExportAndAlignment.setPrefix(this.jTextField_prefix.getText());
            if (mFastaExportAndAlignment.getPrefix() != null && nameOptions.isEmpty()) {
                throw new Exception("Set at least one piece of file name");
            }

            String minL = this.jTextField_minLength.getText();
            if (minL != null && !minL.isEmpty()) {
                try {
                    minLength = Integer.parseInt(minL.trim());
                    mFastaExportAndAlignment.setMinLength(minLength);
                } catch (NumberFormatException nfe) {
                    System.out.println("NumberFormatException: " + nfe.getMessage());
                    throw nfe;
                }
            }

            String maxL = this.jTextField_maxLength.getText();
            if (maxL != null && !maxL.isEmpty()) {
                try {
                    maxLength = Integer.parseInt(maxL.trim());
                    mFastaExportAndAlignment.setMaxLength(maxLength);
                } catch (NumberFormatException nfe) {
                    System.out.println("NumberFormatException: " + nfe.getMessage());
                    throw nfe;
                }
            }

            //test for length range:
            if (minL != null && !minL.isEmpty() && maxL != null && !maxL.isEmpty()) {
                if (minLength > maxLength) {
                    throw new Exception("Minimal length cannot be bigger than maxlength");
                }
            }

            Dictionary MuscleOpt_dic = new Hashtable();
            if (jCheckBox_alignment.isSelected()) {
                muscleFile = prefs.get("MUSCLE_FILE", null);
                if (muscleFile == null || muscleFile.isEmpty()) {
                    throw new Exception("Set Muscle program path in project window");
                }
                mFastaExportAndAlignment.setMuscleFile(muscleFile);
                //mFastaExportAndAlignment.setMuscleOption(jTextField_muscleOptions.getText());

                MuscleOpt_dic.put(MuscleEnum.noanchors, !jCheckBox_anchors.isSelected());
                MuscleOpt_dic.put(MuscleEnum.brenner, jCheckBox_brenner.isSelected());
                //MuscleOpt_dic.put(MuscleEnum.cluster, jCheckBox_cluster.isSelected());
                MuscleOpt_dic.put(MuscleEnum.diags, jCheckBox_diags.isSelected());
                MuscleOpt_dic.put(MuscleEnum.dimer, jCheckBox_dimer.isSelected());

                mFastaExportAndAlignment.setMuscleOption(MuscleOpt_dic);
            }

            //minimal number of sequences:
            try {
                int minNumberOfSeq = 1;
                minNumberOfSeq = Integer.parseInt(jTextField_minNumSeq.getText());
                mFastaExportAndAlignment.setMinNumberOfSeq(minNumberOfSeq);
            } catch (Exception e) {
            }

//            mFastaExportAndAlignment.setUseFile(jCheckBox_file.isSelected());
//            mFastaExportAndAlignment.setUseTag(jCheckBox_tag.isSelected());
//            mFastaExportAndAlignment.setUseSpecies(jCheckBox_species.isSelected());
//            mFastaExportAndAlignment.setUseSeqNumber(jCheckBox_seqNmber.isSelected());



            //minimal variant count:
            try {
                int minVarianNumber = 1;
                minVarianNumber = Integer.parseInt(jTextField_variantCount.getText());
                mFastaExportAndAlignment.setMinVarianCount(minVarianNumber);
            } catch (Exception e) {
            }


            //alignment
            mFastaExportAndAlignment.setAlignment(jCheckBox_alignment.isSelected());

            //reorder align:
            mFastaExportAndAlignment.setReOrderAlign(jCheckBox_sortOrignialFasta.isSelected());


        } catch (Exception e) {
            throw e;
        }
    }

    public void SetsForProcessing(boolean set) {
        if (set) {
            jButton_start.setText("stop");
            jButton_start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmhc/forms/resources/stop16.gif")));
            jButton_close.setEnabled(false);
        } else {
            jButton_start.setText("start");
            jButton_start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmhc/forms/resources/play16.gif")));
            jButton_close.setEnabled(true);
        }
    }

    private void jCheckBox_alignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_alignmentActionPerformed
        if (jCheckBox_alignment.isSelected()) {
            //jCheckBox_alignment.setSelected(jCheckBox_ExportFasta.isSelected());
        }
    }//GEN-LAST:event_jCheckBox_alignmentActionPerformed

    private void jButton_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_closeActionPerformed
        this.setVisible(false);
}//GEN-LAST:event_jButton_closeActionPerformed

    private void jButton_muscleOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_muscleOutputActionPerformed

        JFileChooser chooser = null;
        try {

            chooser = new JFileChooser();
            chooser.setMultiSelectionEnabled(false);
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            String lastDir = this.prefs.get("LAST_OUTPUT_DIR", null);
            if (lastDir != null && !lastDir.isEmpty()) {
                chooser.setCurrentDirectory(new File(lastDir));
            }

            int result = chooser.showOpenDialog(null);
            if (result == JFileChooser.APPROVE_OPTION) {
                File file = chooser.getSelectedFile();
                if (!file.exists()) {
                    throw new Exception("no such file");
                }

                PathChecker pc = new PathChecker(file.getAbsolutePath());
                if (!pc.Check()) {
                    this.jTextField_muscleOutput.setText("");
                    throw new Exception(pc.getMessage());
                }

                this.jTextField_muscleOutput.setText(file.getAbsolutePath());
                prefs.put("LAST_OUTPUT_DIR", jTextField_muscleOutput.getText());
            } else {
            }

        } catch (Exception ex) {
            Logger.getLogger(DBSettings.loggerProgram).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), this.getName(), JOptionPane.ERROR_MESSAGE);
        } finally {
        }
}//GEN-LAST:event_jButton_muscleOutputActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_close;
    private javax.swing.JButton jButton_muscleOutput;
    private javax.swing.JButton jButton_start;
    private javax.swing.JCheckBox jCheckBox_alignment;
    private javax.swing.JCheckBox jCheckBox_anchors;
    private javax.swing.JCheckBox jCheckBox_brenner;
    private javax.swing.JCheckBox jCheckBox_diags;
    private javax.swing.JCheckBox jCheckBox_dimer;
    private javax.swing.JCheckBox jCheckBox_sortOrignialFasta;
    private javax.swing.JComboBox jComboBox_name1;
    private javax.swing.JComboBox jComboBox_name2;
    private javax.swing.JComboBox jComboBox_name3;
    private javax.swing.JComboBox jComboBox_name4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_Main;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    public javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField_maxLength;
    private javax.swing.JTextField jTextField_minLength;
    private javax.swing.JTextField jTextField_minNumSeq;
    private javax.swing.JTextField jTextField_muscleOutput;
    private javax.swing.JTextField jTextField_prefix;
    private javax.swing.JTextField jTextField_variantCount;
    // End of variables declaration//GEN-END:variables
}
